[package]
name = "sol-program-counter"
version = "0.1.0"
edition = "2024"

[lib]
crate-lib = ["cdylib", "lib"]

[dependencies]
borsh = {version = "1.5.7", features=["derive"]}
borsh-derive = "1.5.7"
solana-program = "1.18.26"
